// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBOtNSj8cSu9f_U6lhx2bNVd5Vun-IYyI',
    appId: '1:317016930311:web:b8d92404c7ff9cf15a92a2',
    messagingSenderId: '317016930311',
    projectId: 'first-firebase-project-e3072',
    authDomain: 'first-firebase-project-e3072.firebaseapp.com',
    storageBucket: 'first-firebase-project-e3072.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lLFaYZTLBX8e_15jj1pG9oJuz7iLM6U',
    appId: '1:317016930311:android:90d793ab978023495a92a2',
    messagingSenderId: '317016930311',
    projectId: 'first-firebase-project-e3072',
    storageBucket: 'first-firebase-project-e3072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRk1--rYpP7cnbJ8zh3RDa1vAjD-N_nk',
    appId: '1:317016930311:ios:cf8d56f5f5d4e78b5a92a2',
    messagingSenderId: '317016930311',
    projectId: 'first-firebase-project-e3072',
    storageBucket: 'first-firebase-project-e3072.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRk1--rYpP7cnbJ8zh3RDa1vAjD-N_nk',
    appId: '1:317016930311:ios:a51aad0fffe818eb5a92a2',
    messagingSenderId: '317016930311',
    projectId: 'first-firebase-project-e3072',
    storageBucket: 'first-firebase-project-e3072.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
